### ISSUE TITLE
CAN'T PARSE INFORMATION BETWEEN INTENTS 

### ISSUE THREAD

**Issue by Kairakvo** [software-chasers/Tutor_Tracker#4]
CAN'T USE THE EXTRAS TO PASS BETWEEN INTENTS BETWEEN THE MAIN ACTIVITY AND LOGIN PAGE.

**Comment by potegokgaphola** [comment]
The putExtra and getExtra methods seem to be working fine
![result](https://user-images.githubusercontent.com/47747282/57873332-34124a80-780e-11e9-90b4-5d04e1919b1f.png)
![code](https://user-images.githubusercontent.com/47747282/57873339-3aa0c200-780e-11e9-9169-668352b16eca.png)

**Comment by KhanyileBN** [comment]
Put and get extras are now working.
